### ISSUE TITLE
Class file error

### ISSUE THREAD

**Issue by beltxd** [KwemberDev/BiomeMusic#1]
https://mclo.gs/rRrmlhN

Reproduced with just musify alone. These errors in the log indicate an error in the class file. Reading the logs, it also says 

"[01:25:04] [Client thread/WARN] [FML]: Zip file Musify-0.1.7.jar failed to read properly, it will be ignored"

possibly disabling the mod effectively. That may explain why I wasn't able to get any audios to work within my modpack.

**Comment by KwemberDev** [comment]
Hi!
Thank you for creating this issue, it seems that a log4j module in the meta-inf package not working correctly, i will look into fixing that.

However, even with that warning message the mod should work fine. 
Did you follow the setup instructions in: https://github.com/KwemberDev/BiomeMusic/blob/master/README.md ?

~Kwember.

**Comment by beltxd** [comment]
Thank you for the response. I will share with you my configurations. As an example, I want to make the wither boss fight have music when you fight it.

![image](https://github.com/user-attachments/assets/14c11381-9253-43a2-982e-a47a4d862118)

This is the music placed in the "biomemusic" folder and it is an ogg file.

![image](https://github.com/user-attachments/assets/0d9a66cc-6b5b-490b-bd84-518f2eee7de1)

This is my configuration for it. I have tried, but I might be doing something wrong... Perhaps I need the square brackets around it, but I have tried it, but it still doesn't work for me. Do you mind sharing your configuration if you have made any so that I can try and see where I have gone wrong?

**Comment by KwemberDev** [comment]
Hi,
So small update, i looked into the boss music logic again and you appear to be right, so two things:
1. There was a small oversight on my part, i accidently called the wrong stopmusic method in the boss music handler, which stopped the boss music and not the vanilla music.
2. Do the other music functions work for you? As in the main menu music and the biome music ect?

In any case, a new version with the boss music fixed will be pushed to releases asap, both here on github and on curseforge/modrinth.
Thank you a lot for making this issue, this was indeed a major bug that went through playtesting.
![image](https://github.com/user-attachments/assets/6c39939d-b651-4927-bac5-519267061b23)

**Comment by KwemberDev** [comment]
Alright, the hotfix for the bossmusic is uploaded to github under releases, and is pending for review on curseforge and modrinth. Lets hope curseforge doesnt take a week to approve it again. 

~Kwember.

**Comment by beltxd** [comment]
I will try the other music functions and see if they work, thanks for the changes

**Comment by beltxd** [comment]
On a side note, the boss music does now work, however, there seems to be some log spamming. It will continuously repeat the log report even when the boss is dead

https://mclo.gs/Gg3ZrPL

**Comment by KwemberDev** [comment]
oh fgs, im so stupid.

Sorry, it appears i left a singular debug line in by accident, thank you for noticing.
I will fix this and (again) push the latest version as soon as possible.

**Comment by beltxd** [comment]
Awesome, on a positive note now, all of the sounds for the different categories work fine, which is good!

**Comment by KwemberDev** [comment]
Alright, good to hear. 
Also, i have figured out a fix for the class file errors in console, the final and last release hotfix (version 0.1.8) has been uploaded to github and is pending on curseforge and modrinth.

**Comment by beltxd** [comment]
I also would like to make a suggestion, perhaps for a later update, could the boss music also have a configuration that the music would only activate if aggroed by the player?

Additionally is it possible to set a biome to have multiple music lists?
![image](https://github.com/user-attachments/assets/d9536f72-459c-4f80-8b26-c8c5b510f059)
As you can see in each of these biomes there are 4 ogg files added in this array and I was hoping that there was a chance that there would be variability on what music would be played. However, this config only recognizes the first song and will keep looping it. Sometimes it does work, but other times, the music just fades out and plays another track. I think it's processing all the .ogg files at once and not letting the other music files finish playing.

**Comment by KwemberDev** [comment]
boss music only playing when aggro'd to the player is something i could add, but im not sure if its the better option, this would mean that when fighting a boss with multiple players, only one player would have music. perhaps there is a way around that, i will put it on the list of future additions.

Also, biomes will play a random song from the list, you are not supposed to put any spaces between the song names. Might be my oversight, i could maybe include a disclaimer about that, or work in that it ignores spaces.
your config should work like this:
S:"mm:azure"=vaguehopeinstrumental.ogg,aotambient1.ogg,nierambience.ogg,aotambient2.ogg
^ no spaces between the song names.

If a song from the songlist of the biome is already playing, it keeps playing the song (because the song is one of the songs for that biome.) 

As for repeating the song, i did think about making that a config option and have it randomly choose a song again after the end of a music file, i suppose that would be another future addition.

**Comment by beltxd** [comment]
Ah ok, for the biome music, now it's properly sorted, it only plays a song randomly from the list, but it will keep on looping the song after it ends. But, if I rejoin the world or re enter a biome after leaving, it plays a different song sometimes, but it will repeat the song again and again until I rejoin the world or re enter a biome. The songlist recognizes that there are multiple songs, but it only chooses to play one that it chooses over and over again from what I've gathered. Not sure if this is intended.

**Comment by KwemberDev** [comment]
ah i see what you mean. The song repeating was what i set up, but in hindsight it mightve not been a good decision as it can get a bit annoying that it repeats the same song. i will prepare an update that will make it randomly pick a new song again instead of looping.

**Comment by beltxd** [comment]
As for the boss suggestion, the reason why I made the suggestion was because some bosses in my modpack spawn as soon as you get within a certain distance, therefore you could be outside of the boss room and it would play the boss music without actually fighting it.

**Comment by KwemberDev** [comment]
You could try lowering the boss music activation range, if that doesnt interfere with the attack range of other bosses i suppose.

**Comment by KwemberDev** [comment]
A new version has been uploaded to github and is pending on curseforge and modrinth. It stops music from auto-repeating and has some improvements to the combat music aggro counter.
